version: '3.2'

services:
  post:
    build: ./gateway
    image: post-gt
    command: ["npm", "run", "apm"]
    ports:
      - "3000:3000"
    environment:
      - FASTIFY_PORT=3000
    volumes:
      - ./post/:/usr/src/app
      - /usr/src/app/node_modules

  post:
    build: ./post
    image: post-gt
    command: ["npm", "run", "apm"]
    ports:
      - "3030:3030"
    environment:
      - FASTIFY_PORT=3030
    volumes:
      - ./post/:/usr/src/app
      - /usr/src/app/node_modules

  me:
    build: ./me
    image: me-gt
    command: ["npm", "run", "apm"]
    ports:
      - "3031:3031"
    environment:
      - FASTIFY_PORT=3031
    volumes:
      - ./post/:/usr/src/app
      - /usr/src/app/node_modules

  timeline:
    build: ./timeline
    image: timeline-gt
    command: ["npm", "run", "apm"]
    ports:
      - "3032:3032"
    environment:
      - FASTIFY_PORT=3032
    volumes:
      - ./post/:/usr/src/app
      - /usr/src/app/node_modules
